
p
"	*Î^À≤Åambition_PowerInfluenceJ
 THRONE_ROOM_POWER_CATEGORY_TITLE&THRONE_ROOM_POWER_CATEGORY_DESCRIPTION
y
#	$u*ß”ﬁambition_KnowledgeWisdomR
$THRONE_ROOM_KNOWLEDGE_CATEGORY_TITLE*THRONE_ROOM_KNOWLEDGE_CATEGORY_DESCRIPTION
l
	ÚúodÒB&ambition_HonorGloryJ
 THRONE_ROOM_HONOR_CATEGORY_TITLE&THRONE_ROOM_HONOR_CATEGORY_DESCRIPTION
~
(	Hd´DxøX}ambition_AdventureExplorationR
$THRONE_ROOM_ADVENTURE_CATEGORY_TITLE*THRONE_ROOM_ADVENTURE_CATEGORY_DESCRIPTION