
t
 	Y9—Ê÷edhistory_NobleCourtierP
#THRONE_ROOM_COURTIER_CATEGORY_TITLE)THRONE_ROOM_COURTIER_CATEGORY_DESCRIPTION
r
 	§j@Á|™¥ghistory_SecretBastardN
"THRONE_ROOM_BASTARD_CATEGORY_TITLE(THRONE_ROOM_BASTARD_CATEGORY_DESCRIPTION
o
!	 ¨¼âíˆ¸history_WanderingExileJ
 THRONE_ROOM_EXILE_CATEGORY_TITLE&THRONE_ROOM_EXILE_CATEGORY_DESCRIPTION
r
 	g¥#¦äÚ²history_DragonScholarN
"THRONE_ROOM_SCHOLAR_CATEGORY_TITLE(THRONE_ROOM_SCHOLAR_CATEGORY_DESCRIPTION